# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  #adapter: sqlite3
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #timeout: 5000
  adapter: mysql2
  encodding: utf8
  database: crawler
  pool: 5
  username: root
  password:
  host: localhost

development:
  adapter: mysql2
  encodding: utf8
  database: crawler
  pool: 5
  username: root
  password:
  host: localhost


production:
  adapter: mysql2
  encodding: utf8
  database: crawler
  pool: 5
  username: root
  password:
  host: localhost
